### ISSUE TITLE
Feature request: Add a "links" field on each program's JSON

### ISSUE THREAD

**Issue by itaranto** [b3nj5m1n/xdg-ninja#169]
Like the title says, having a dedicated field for issue links would be nice for tracking.

**Comment by b3nj5m1n** [comment]
Tbh I don't think this is something that should be added since it would require "rewriting" all the existing configs (even though you could automate it) and, more importantly, because I think it adds complexity to the process of adding a new configuration, and my main goal is to make that as easy as possible to encourage contributions.

It shouldn't be too hard to extract the links automatically, though, so I don't think you even need to have a dedicated field.

I'll close this for now, if you disagree with me, feel free to reopen.
