### ISSUE TITLE
Add more rules from doron-cohen/antidot

### ISSUE THREAD

**Issue by telans** [b3nj5m1n/xdg-ninja#2]
Thanks for this program, it has a lot of nice rules. [Antidot](https://github.com/doron-cohen/antidot) is another program which aims to reduce the clutter in $HOME.

I've noticed it has some rules that this program does not. The ones I spotted were:

```
bash_history
ccache
fontconfig
fonts
gdb-init
gem
gitconfig
httpie
less
lnav
mapscii
pex
pylint
screen
tig-history
weechat
qrpc
chez
```

https://github.com/doron-cohen/antidot/blob/master/rules.yaml

**Comment by b3nj5m1n** [comment]
That's very cool, I'll have a look at it when I get the chance since it's quite a lot, or maybe try to write a script that automatically converts it to configuration for this tool.

**Comment by Scr0nch** [comment]
I wrote [a program](https://gitlab.com/Scr0nch/antidot-to-xdg-ninja-config-transformer/) that should reduce the boring manual labor for this task. Manual review of the files it generates is necessary because the help text may be a bit robotic in complicated cases. In simple cases, it matches the current style. Whenever an Antidot rule with a `notes` field is encountered, a warning is logged since they cannot be automatically converted well. Also, since Antidot sometimes names their configurations differently, program configurations may be duplicated with different names, e.g. `cargo` and `cargo_home`.

As a side note, I know that Rust is overkill for a task like this, but I've been meaning to give it a try for a while and this seemed like a simple enough project to start with.

**Comment by b3nj5m1n** [comment]
@Scr0nch This is awesome, thank you so much!

Don't worry about the trying out rust part - the Haskell I wrote for this was the first program I've ever written in Haskell, except for a handful of advent of code challenges. Also, your rust doesn't look bad to me at all, although my experience with it is fairly limited.

It might be a day or two until I can take a look at this myself, so if anyone wants to submit a PR for the configs generated by this, that would be very helpful.

Thanks again!

**Comment by b3nj5m1n** [comment]
I finally got around to going through them, thanks again @Scr0nch.
