### ISSUE TITLE
Hide blocked files

### ISSUE THREAD

**Issue by FineFindus** [b3nj5m1n/xdg-ninja#251]
I would like to see a flag, to hide files, which have still open issue, and cannot be moved. This would considerably declutter the screen and help take action on the leftover items.

**Comment by b3nj5m1n** [comment]
Use the `--skip-unsupported` flag.

**Comment by FineFindus** [comment]
Thanks for the quick response, when was this feature introduced? It does not seem to be available in my version.

**Comment by b3nj5m1n** [comment]
I think it was introduced about 5 months ago, so if you're using a packaged version it's probably not up to date.

This is a big issue with the packaging of this project, since the releases aren't meant for releases of the script itself, see #204.

For now, I'm afraid your best bet is to clone the repository manually.
