### ISSUE TITLE
bat version compatibility

### ISSUE THREAD

**Issue by Ballasi** [b3nj5m1n/xdg-ninja#34]
I have a small concern on bat compatibility on the program, the flag `-f` used in the bat call has been implemented in version [0.16.0](https://github.com/sharkdp/bat/releases/tag/v0.16.0) while some distributions downloads lower versions on their package manager (see https://repology.org/project/bat-cat/versions), for instance, Ubuntu 21.10 (on apt) installing version 0.12.1 of `bat`.

On my side, I don't see any difference with and without the `-f` flag, and I would believe it is the same. @pvonmoradi can you confirm?

If this is, in fact, useful, it would probably be best to check the availability of this flag.

**Comment by pvonmoradi** [comment]
Since at that point of the code, the output is being printed directly to an interactive tty, `bat` uses colorization. However, if the code is changed into this:
```sh
a=$(printf "%s\n" "$HELP" | bat -pp --language markdown)
printf "%s" "$a"
```
Then colorization is deactivated cause `-f` is not provided.
To accomodate for older versions of bat, we can use `--decorations=always --color=always` in place of `-f`. Either that, or we can remove this switch altogether but remember to not redirect `printf | bat` to anything other than an interactive tty.

 `bat`'s manpage:
```
       -f, --force-colorization

              Alias for '--decorations=always --color=always'. This is useful if
              the  output  of  bat  is piped to another program, but you want to
              keep the colorization/decorations.
```

**Comment by Ballasi** [comment]
I feel like there would be no use for us to redirect to a variable other than for instance redirecting to a file (or directly do `./xdg-ninja.sh > output`).

It is unlikely to do so but plausible, I would by myself disable this **BUT**, in this case, the rest of the program forces coloration (e.g., XDG env variables warning), so it makes sense to force bat to do so.

I think replacing `-f` to `--decorations=always --color=always` is what is best in that case, and that if there is a need for file redirection in the future, it would be best to add a `--disable-color` argument in the command.
