### ISSUE TITLE
Where to set required environment variables?

### ISSUE THREAD

**Issue by samarth-ba** [b3nj5m1n/xdg-ninja#41]
```
The $XDG_DATA_HOME environment variable is not set, make sure to add it to your shell's configuration before setting any of the other environment variables!
    ⤷ The recommended value is: $HOME/.local/share
The $XDG_CONFIG_HOME environment variable is not set, make sure to add it to your shell's configuration before setting any of the other environment variables!
    ⤷ The recommended value is: $HOME/.config
The $XDG_STATE_HOME environment variable is not set, make sure to add it to your shell's configuration before setting any of the other environment variables!
    ⤷ The recommended value is: $HOME/.local/state
The $XDG_CACHE_HOME environment variable is not set, make sure to add it to your shell's configuration before setting any of the other environment variables!
    ⤷ The recommended value is: $HOME/.cache
```
I want to fix this error, so I can set the rest of the variables required, but I don't know where to set them.

I tried in `/etc/environment`, `~/.bashrc`, `~/.profile` and `~/.bash_profile`, but neither of them worked.

Would you please give me a hint as to where I should look for the answer?

Thanks in advance.

Edit: I'm using Arch Linux and the AUR version of the script.

**Comment by Willenbrink** [comment]
I don't use bash myself but generally you've already put it in the correct place. Unfortunately bash does not automatically update it's configuration so you need to `source ~/.bashrc` (or one of the other files) for the changes to take effect (or logout and login).

You can also read more on the arch wiki on e.g. [per user configuration](https://wiki.archlinux.org/title/Environment_variables#Per_user)

**Comment by samarth-ba** [comment]
> 

I tried logging out and logging back in, and sourcing the files. Neither worked. Thanks anyway.

**Comment by Willenbrink** [comment]
Well, in that case there are multiple possible error sources.

The command should be `export XDG_CONFIG_HOME=~/.config`. Does this work when you enter it into the shell? Note that there are no spaces around the = and there is no $ before the variable. Check the result by rerunning xdg_ninja.sh or `echo $XDG_CONFIG_HOME`

If that does work ensure that you have written exactly that command into a file, e.g. .bashrc. `source` that file (this basically runs every command in the file). Does this work too?

Also, IMHO you will likely have more success googling as this is a common question or asking on the Arch forum/StackOverflow as this is an issue tracker for this project and this issue seems unrelated.
