### ISSUE TITLE
recommend XDG default dirs via parameter expansion

### ISSUE THREAD

**Issue by emorrp1** [b3nj5m1n/xdg-ninja#8]
Wherever you're using `"$XDG_CONFIG_DIR"`, use `"${XDG_CONFIG_DIR:-"$HOME/.config"}"` (ditto [for the others](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables)) - this is [in POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02) so will work regardless of which shell, which you're already assuming by using `export`. An alternative to this would be to unconditionally recommend adding this to the shell rc:

`: "${XDG_CONFIG_HOME:="$HOME/.config"}"`

**Comment by b3nj5m1n** [comment]
I think most people using this tool are probably explicitly exporting the XDG vars, so I'm not sure how useful this would be.

A user on reddit already suggested emitting a warning when running the script and the XDG vars aren't set properly, and I think that's probably a better solution, since the approach you suggested would require lots of manual changes.

Let me know what you think!

**Comment by oberon227** [comment]
Came here to say: Love the tool, but was left a little clueless as to what $XDG_CONFIG_HOME was _supposed_ to be.

So emitting a warning when XDG vars aren't set, and providing a link to what they should be (or just letting us know what they should be) would be quite helpful.  Because I'm not (yet) explicitly exporting the XDG vars.

Thank you so much for doing this! :1st_place_medal:

**Comment by b3nj5m1n** [comment]
I added this in 1b217566378de9954d4459a9a509841f8019e088.

Would be great if you could try it out and give me some feedback!

**Comment by oberon227** [comment]
That looks good!

To keep with the "recommendation" nature of the rest of the tool, I'd suggest putting a whole example `export XDG_CONFIG_HOME=$HOME/.config` on that second line after the arrow, and maybe the recommended file to put them in.  (I think I'm discovering that's .bash_profile, or .xinitrc)

**Comment by b3nj5m1n** [comment]
I think we can close this since we detect if the variables are not set.

If you disagree, feel free to reopen.

**Comment by jvschiavo** [comment]
> I'd suggest putting a whole example `export XDG_CONFIG_HOME=$HOME/.config` on that second line after the arrow, and maybe the recommended file to put them in. (I think I'm discovering that's .bash_profile, or .xinitrc)

I like this idea. I'm still not sure which is the most appropriate file to export the variables.
