### ISSUE TITLE
Add option to hide unsupported files and directories

### ISSUE THREAD

**Issue by aflyingpumpkin** [b3nj5m1n/xdg-ninja#93]
As the title says. This would be useful for a couple of different uses cases, such as:
- Users who use the command in `watch` to get live updates.
- Users who want a de-cluttered output.

**Comment by b3nj5m1n** [comment]
This is a very good idea and definitely something I'd merge.

I'll probably implement this myself in a couple of days when I have the time, in the meantime I'm open to PRs.

Thanks for the suggestion!

**Comment by SaphireLattice** [comment]
Gonna chime in with agreement on this. Had to quickly edit the script up to have `$SKIP_IMMOVABLE`, sorry for the badly named hack x3

Also another pain is that uhhh, well, it would be really nice to actually have the variable info separate or such, so that you could tell it to output a `.bashrc`/etc drop in file, with comments detailing what it is for, and if there are any possible caveats and commenting it out by default for that

Maybe also give a "migration" command too, like, just a bunch of `mv`s for supported dirs that don't have "gotchas"

**Comment by b3nj5m1n** [comment]
> I'll probably implement this myself in a couple of days when I have the time

Well, sorry about that.

Anyways, it's implemented with 193c1d3 and fea5aa5, you can now use `--skip-unsupported`.

Let me know if you encounter any problems.
