### ISSUE TITLE
Exit status dependent upon amount of fixable files in homedir

### ISSUE THREAD

**Issue by aflyingpumpkin** [b3nj5m1n/xdg-ninja#94]
This would allow for slightly easier scripting using the program.

Example of a cronjob that could be created using this feature:
```sh
@weekly xdg-ninja.sh || notify-send "Unnecessary dot files in homedir" "You have $@ unnecessary files in your home directory."
```

Currently a user would have to create a rather-long wrapper program that finds the amount of red ansi codes which is not preferable.

**Comment by b3nj5m1n** [comment]
I've actually thought about this exact thing before, but I was too lazy to implement it, since I basically have what you described in my dotfiles. (See [here](https://github.com/b3nj5m1n/dotfiles/blob/2da4f05b2be9c2c743a647abb77115e6e42532b4/files/zsh/zshrc#L8) to see what I mean, basically a message I get when I open up a new shell that tells me if new files have appeared in the home dir.

I'd definitely be open to a PR for this.

**Comment by Breigner01** [comment]
Could I suggest creating a cli option to xdg-ninja, something like `--show-only-amount`that would print the line `You have X dotfiles in your home`.
That prevents from using the return value of the program (which when different than 0 suggests an error happened during execution), so it would let the place for error codes when needed and allow for versatility if needed. So in the future it could have some more cli features like maybe excluding the stuff that can't be fixed from output or whatever option or maybe exclude certain dotfiles because it can't be fixed on your end.
Plus it would simplify what you put in your shell rc file.

**Comment by b3nj5m1n** [comment]
I added this with fbd1432, let me know if you encounter any problems.

I might think about adding more control options like @Breigner01 suggested in the future.
